name: Application lint checks

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: whoami

  # lint-check:
  #   runs-on: ubuntu-latest

  #   outputs:
  #     apps: ${{ steps.set-matrix.outputs.apps }}

  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - uses: pnpm/action-setup@v3
  #       with:
  #         version: 9

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 24
  #         cache: 'pnpm'

  #     - run: pnpm install --frozen-lockfile

  #     - name: Check all linting
  #       run: pnpm nx affected --target=lint --base=origin/main --head=HEAD

  # frontend-build:
  #   needs: lint-check
  #   runs-on: ubuntu-latest
  #   outputs:
  #     apps: ${{ steps.get-nextjs-apps.outputs.apps }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - uses: pnpm/action-setup@v3
  #       with:
  #         version: 9

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 24
  #         cache: 'pnpm'

  #     - run: pnpm install --frozen-lockfile

  #     - name: Get affected production apps
  #       id: get-nextjs-apps
  #       run: |
  #         affected=$(pnpm nx show projects --affected --projects=tag:framework:nextjs --json --base=origin/main --head=HEAD)

  #         # If empty, return empty array instead of blank
  #         if [ -z "$affected" ]; then
  #           affected="[]"
  #         fi

  #         echo "apps=$affected" >> $GITHUB_OUTPUT

  # build-frontend-apps:
  #   needs: frontend-build
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       app: ${{ fromJson(needs.frontend-build.outputs.apps) }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - uses: pnpm/action-setup@v3
  #       with:
  #         version: 9

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 24
  #         cache: 'pnpm'

  #     - run: pnpm install --frozen-lockfile

  #     - name: Login to Docker registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: registry.falcon-head.org
  #         username: ${{ vars.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build affected Next.js app
  #       run: pnpm nx build ${{ matrix.app }} --skip-nx-cache

  #     # - name: Extract app name
  #     #   id: extract
  #     #   run: |
  #     #     RAW="${{ matrix.app }}"
  #     #     APP_NAME="${RAW##*/}"
  #     #     echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT

  #     # - name: Build and push Docker image
  #     #   run: |
  #     #     docker build -t registry.falcon-head.org/${{ steps.extract.outputs.app_name }}:${{ github.event.pull_request.number }} -f ./infra/Dockerfiles/NextApp.Dockerfile --build-arg APP_NAME=${{ steps.extract.outputs.app_name }} .
  #     #     docker push registry.falcon-head.org/${{ steps.extract.outputs.app_name }}:${{ github.event.pull_request.number }}

  #     - name: Execute remote SSH commands using SSH key
  #       uses: appleboy/ssh-action@v1
  #       with:
  #         host: ${{ vars.SSH_HOST }}
  #         username: ${{ vars.SSH_USERNAME }}
  #         port: ${{ vars.PORT }}
  #         key: ${{ secrets.SSH_KEY }}
  #         script: whoami
